-- ~/.config/nvim/lua/plugins/which-key.lua
return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "helix",
    delay = 300,
    spec = {
      {
        mode = { "n", "v" },
        { "<leader>e",  desc = "文件树" },
        { "<leader>o",  desc = "代码大纲" },
        { "<leader>b",  group = "Buffer" },
        { "<leader>bd", desc = "关闭 Buffer" },
        { "<leader>bq", desc = "强制关闭" },
        { "<leader>bp", desc = "Buffer 左移" },
        { "<leader>bn", desc = "Buffer 右移" },
        { "<leader>c",  group = "代码" },
        { "<leader>cf", desc = "格式化代码" },
        { "<leader>ca", desc = "自动修复" },
        { "<leader>cs", desc = "代码符号" },
        { "<leader>f",  group = "搜索" },
        { "<leader>ff", desc = "查找文件" },
        { "<leader>fg", desc = "全文搜索" },
        { "<leader>fb", desc = "切换 Buffer" },
        { "<leader>fr", desc = "最近文件" },
        { "<leader>fh", desc = "帮助文档" },
        { "<leader>fk", desc = "查看快捷键" },
        { "<leader>fd", desc = "诊断列表" },
        { "<leader>h",  group = "Git" },
        { "<leader>hs", desc = "暂存修改" },
        { "<leader>hr", desc = "撤销修改" },
        { "<leader>hS", desc = "暂存全部" },
        { "<leader>hb", desc = "行 Blame" },
        { "<leader>hd", desc = "文件差异" },
        { "<leader>hp", desc = "预览修改" },
        { "<leader>t",  group = "终端" },
        { "<leader>tt", desc = "底部终端" },
        { "<leader>tf", desc = "浮动终端" },
        { "<leader>r",  group = "重构" },
        { "<leader>rn", desc = "重命名符号" },
        { "<leader>d",  group = "调试" },
        { "<leader>db", desc = "断点切换" },
        { "<leader>dc", desc = "开始/继续" },
        { "<leader>dC", desc = "终止调试" },
        { "<leader>do", desc = "单步跳过" },
        { "<leader>di", desc = "单步进入" },
        { "<leader>dO", desc = "单步跳出" },
        { "<leader>du", desc = "调试面板" },
        { "<leader>dh", desc = "悬浮变量" },
        { "<leader>s",  group = "窗口" },
        { "<leader>sv", desc = "垂直分割" },
        { "<leader>sh", desc = "水平分割" },
        { "<leader>x",  group = "诊断" },
        { "<leader>xx", desc = "全部诊断" },
        { "<leader>xX", desc = "当前文件" },
        { "<leader>w",  group = "窗口操作", proxy = "<C-w>" },
        { "[", group = "上一个" },
        { "[b", desc = "Buffer" },
        { "[c", desc = "Git 修改" },
        { "[d", desc = "诊断" },
        { "]", group = "下一个" },
        { "]b", desc = "Buffer" },
        { "]c", desc = "Git 修改" },
        { "]d", desc = "诊断" },
        { "g",  group = "跳转" },
        { "gd", desc = "跳转定义" },
        { "gD", desc = "跳转声明" },
        { "gr", desc = "查找引用" },
        { "gi", desc = "跳转实现" },
        { "e",  desc = "快速跳转", mode = { "n", "x", "o" } },
        { "S",  desc = "语法树跳转",       mode = { "n", "x", "o" } },
        { "K",  desc = "悬浮文档" },
        { "<CR>",  desc = "开始/扩大选择", mode = { "n", "v" } },
        { "<BS>",  desc = "缩小选择",       mode = "v" },
        { "<TAB>", desc = "扩大到作用域",   mode = "v" },
      },
      {
        mode = "i",
        { "<C-Space>", desc = "打开补全" },
        { "<C-e>",     desc = "关闭补全" },
        { "<C-k>",     desc = "签名帮助" },
      },
    },
  },
}
